// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUOk9ccVo-sJFzSPRiebYKHoZSrDl77Uk',
    appId: '1:293669249461:web:e0e75e118f394b6e0ef9fc',
    messagingSenderId: '293669249461',
    projectId: 'authentication-d5243',
    authDomain: 'authentication-d5243.firebaseapp.com',
    storageBucket: 'authentication-d5243.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcRWr_TU-aVgIVu_vJ7D-TZ6lEOG_eRf0',
    appId: '1:293669249461:android:5aee898355bbf67f0ef9fc',
    messagingSenderId: '293669249461',
    projectId: 'authentication-d5243',
    storageBucket: 'authentication-d5243.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYmJhe2Iz5bkgI7uV9RjvXfjNHdZvVQeU',
    appId: '1:293669249461:ios:51f7140b6666a35a0ef9fc',
    messagingSenderId: '293669249461',
    projectId: 'authentication-d5243',
    storageBucket: 'authentication-d5243.firebasestorage.app',
    iosBundleId: 'com.example.aunth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUOk9ccVo-sJFzSPRiebYKHoZSrDl77Uk',
    appId: '1:293669249461:web:b7af6c3c550e312a0ef9fc',
    messagingSenderId: '293669249461',
    projectId: 'authentication-d5243',
    authDomain: 'authentication-d5243.firebaseapp.com',
    storageBucket: 'authentication-d5243.firebasestorage.app',
  );
}
